params [["_unitObject",objNull],["_unitClass",""]];

if (_unitObject isEqualTo objNull) exitWith {};
if (_unitClass isEqualTo "") exitWith {};

_loadOut = [];
switch _unitClass do
{
	case "squadLeader": {_loadOut = [["SMA_M4_GL","SMA_supp2smaB_556","SMA_SFPEQ_M4TOP_BLK","SMA_ELCAN_SPECTER_ARDRDS_4z",["SMA_30Rnd_556x45_M855A1",30],["1Rnd_HE_Grenade_shell",1],""],[],["rhsusf_weap_glock17g4","rhsusf_acc_omega9k","","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],["UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve_RM",[["ACE_fieldDressing",16],["ACE_CableTie",1],["ACE_EarPlugs",1],["ACE_epinephrine",5],["ACE_Flashlight_XL50",1],["ACE_morphine",16]]],["UK3CB_BAF_V_Osprey_Grenadier_A",[["SMA_30Rnd_556x45_M855A1",8,30],["SMA_30Rnd_556x45_M855A1_Tracer",4,30],["1Rnd_HE_Grenade_shell",10,1],["1Rnd_SmokeYellow_Grenade_shell",2,1],["1Rnd_SmokeRed_Grenade_shell",2,1],["1Rnd_SmokeGreen_Grenade_shell",2,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17],["SmokeShellYellow",2,1]]],["UK3CB_BAF_B_Bergen_MTP_JTAC_L_A",[["ACE_bloodIV",1],["ACE_bloodIV_250",1],["ACE_bloodIV_500",1],["ACE_CableTie",1],["ACE_EntrenchingTool",1],["ACE_Kestrel4500",1],["ACE_MapTools",1],["ACE_SpraypaintRed",1],["ACE_RangeCard",1],["SmokeShellYellow",4,1],["HandGrenade",3,1]]],"UK3CB_BAF_H_Beret_SAS_PRR","VSM_Shemagh_glasses_tan",["Laserdesignator_01_khk_F","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch",""]]};
	case "teamLeader": {_loadOut = [["SMA_M4_GL","SMA_supp2smaB_556","SMA_SFPEQ_M4TOP_BLK","SMA_ELCAN_SPECTER_ARDRDS_4z",["SMA_30Rnd_556x45_M855A1",30],["1Rnd_HE_Grenade_shell",1],""],[],["rhsusf_weap_glock17g4","rhsusf_acc_omega9k","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve_RM",[["ACE_fieldDressing",16],["ACE_CableTie",1],["ACE_EarPlugs",1],["ACE_epinephrine",5],["ACE_Flashlight_XL50",1],["ACE_morphine",16]]],["UK3CB_BAF_V_Osprey_SL_C",[["1Rnd_HE_Grenade_shell",10,1],["SMA_30Rnd_556x45_M855A1",8,30],["SMA_30Rnd_556x45_M855A1_Tracer",4,30],["1Rnd_SmokeGreen_Grenade_shell",2,1],["1Rnd_SmokeRed_Grenade_shell",2,1],["1Rnd_SmokeYellow_Grenade_shell",2,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17],["SmokeShellYellow",2,1]]],["UK3CB_BAF_B_Bergen_MTP_SL_L_A",[["ACE_bloodIV",1],["ACE_bloodIV_250",1],["ACE_bloodIV_500",1],["ACE_CableTie",1],["ACE_EntrenchingTool",1],["ACE_SpraypaintGreen",1],["ACE_MapTools",1],["SmokeShellYellow",4,1],["HandGrenade",3,1],["1Rnd_HE_Grenade_shell",5,1],["SmokeShellGreen",2,1],["SmokeShellOrange",2,1]]],"UK3CB_BAF_H_Boonie_MTP","VSM_Shemagh_glasses_tan",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch",""]]};
	case "autoRiflemanM249": {_loadOut = [["rhs_weap_m249_light_L_vfg2","ACE_muzzle_mzls_L","SMA_ANPEQ15_BLK","rhsusf_acc_ACOG3",["rhsusf_200Rnd_556x45_box",200],[],"rhsusf_acc_saw_lw_bipod"],[],["rhsusf_weap_glock17g4","rhsusf_acc_omega9k","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve",[["ACE_fieldDressing",16],["ACE_CableTie",1],["ACE_EarPlugs",1],["ACE_epinephrine",5],["ACE_Flashlight_XL50",1],["ACE_morphine",16]]],["UK3CB_BAF_V_Osprey_MG_B",[["rhsusf_200Rnd_556x45_box",2,200],["rhsusf_200rnd_556x45_M855_mixed_box",1,200],["rhsusf_mag_17Rnd_9x19_FMJ",2,17],["SmokeShellYellow",3,1]]],["UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D",[["ACE_bloodIV",1],["ACE_bloodIV_250",1],["ACE_bloodIV_500",1],["ACE_CableTie",2],["ACE_EntrenchingTool",1],["SmokeShellYellow",3,1],["HandGrenade",3,1],["rhsusf_200rnd_556x45_M855_box",2,200]]],"UK3CB_BAF_H_Boonie_MTP_PRR","VSM_Shemagh_glasses_tan",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch",""]]};
	case "engineer": {_loadOut = [["SMA_M4MOE_SM","SMA_supp2smaB_556","SMA_SFPEQ_M4TOP_BLK","SMA_ELCAN_SPECTER_ARDRDS_4z",["SMA_30Rnd_556x45_M855A1",30],[],"SMA_Gripod_01"],[],["ACE_VMH3","","","",[],[],""],["UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve_RM",[["ACE_fieldDressing",15],["ACE_CableTie",1],["ACE_EarPlugs",1],["ACE_epinephrine",5],["ACE_Flashlight_XL50",1],["ACE_morphine",17]]],["UK3CB_BAF_V_Osprey_Rifleman_E",[["SMA_30Rnd_556x45_M855A1",10,30],["SMA_30Rnd_556x45_M855A1_Tracer",4,30],["SmokeShellYellow",4,1],["HandGrenade",1,1]]],["UK3CB_BAF_B_Bergen_MTP_Sapper_L_A",[["ACE_DefusalKit",1],["ACE_EntrenchingTool",1],["ACE_CableTie",2],["ACE_SpraypaintBlue",1],["ACE_bloodIV_500",1],["ACE_bloodIV_250",1],["ACE_bloodIV",1],["ACE_wirecutter",1],["ACE_M26_Clacker",1],["SmokeShellYellow",2,1],["HandGrenade",1,1],["DemoCharge_Remote_Mag",2,1]]],"UK3CB_BAF_H_Boonie_MTP_PRR","VSM_Shemagh_glasses_tan",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch",""]]};
	case "grenadier": {_loadOut = [["SMA_M4_GL","SMA_supp2smaB_556","SMA_SFPEQ_M4TOP_BLK","SMA_ELCAN_SPECTER_ARDRDS_4z",["SMA_30Rnd_556x45_M855A1",30],["1Rnd_HE_Grenade_shell",1],""],[],["rhsusf_weap_glock17g4","rhsusf_acc_omega9k","","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],["UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve",[["ACE_fieldDressing",16],["ACE_CableTie",1],["ACE_EarPlugs",1],["ACE_epinephrine",5],["ACE_Flashlight_XL50",1],["ACE_morphine",16]]],["UK3CB_BAF_V_Osprey_Grenadier_B",[["SMA_30Rnd_556x45_M855A1",10,30],["SMA_30Rnd_556x45_M855A1_Tracer",4,30],["1Rnd_HE_Grenade_shell",10,1],["SmokeShellYellow",4,1],["HandGrenade",1,1]]],["UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D",[["ACE_bloodIV",1],["ACE_bloodIV_250",1],["ACE_bloodIV_500",1],["ACE_SpraypaintBlue",1],["ACE_CableTie",2],["ACE_EntrenchingTool",1],["SmokeShellYellow",2,1],["HandGrenade",2,1],["1Rnd_HE_Grenade_shell",15,1],["1Rnd_SmokeYellow_Grenade_shell",2,1],["1Rnd_SmokeRed_Grenade_shell",2,1],["1Rnd_SmokeGreen_Grenade_shell",2,1]]],"UK3CB_BAF_H_Boonie_MTP_PRR","VSM_Shemagh_Glasses_OD",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch",""]]};
	case "combatMedic": {_loadOut = [["SMA_M4MOE_SM","SMA_supp2smaB_556","SMA_SFPEQ_M4TOP_BLK","SMA_ELCAN_SPECTER_ARDRDS_4z",["SMA_30Rnd_556x45_M855A1",30],[],"SMA_Gripod_01"],[],["rhsusf_weap_glock17g4","rhsusf_acc_omega9k","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve_RM",[["ACE_fieldDressing",16],["ACE_CableTie",1],["ACE_EarPlugs",1],["ACE_epinephrine",5],["ACE_Flashlight_XL50",1],["ACE_morphine",16]]],["UK3CB_BAF_V_Osprey_Medic_D",[["SMA_30Rnd_556x45_M855A1",10,30],["SMA_30Rnd_556x45_M855A1_Tracer",4,30],["SmokeShellYellow",6,1],["HandGrenade",3,1],["SmokeShellBlue",2,1]]],["UK3CB_BAF_B_Bergen_MTP_Medic_L_A",[["ACE_bloodIV",10],["ACE_bloodIV_250",10],["ACE_bloodIV_500",10],["ACE_CableTie",2],["ACE_epinephrine",5],["ACE_fieldDressing",20],["ACE_morphine",20]]],"UK3CB_BAF_H_Beret_SAS_PRR","VSM_Shemagh_Glasses_OD",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch",""]]};
	case "jtac": {_loadOut = [["SMA_M4_GL","SMA_supp2smaB_556","SMA_SFPEQ_M4TOP_BLK","SMA_ELCAN_SPECTER_ARDRDS_4z",["SMA_30Rnd_556x45_M855A1",30],["1Rnd_HE_Grenade_shell",1],""],[],["rhsusf_weap_glock17g4","rhsusf_acc_omega9k","","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],["UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve_RM",[["ACE_fieldDressing",16],["ACE_CableTie",1],["ACE_EarPlugs",1],["ACE_epinephrine",5],["ACE_Flashlight_XL50",1],["ACE_morphine",16]]],["UK3CB_BAF_V_Osprey_Grenadier_A",[["SMA_30Rnd_556x45_M855A1",8,30],["SMA_30Rnd_556x45_M855A1_Tracer",4,30],["1Rnd_HE_Grenade_shell",10,1],["1Rnd_SmokeYellow_Grenade_shell",2,1],["1Rnd_SmokeRed_Grenade_shell",2,1],["1Rnd_SmokeGreen_Grenade_shell",2,1],["rhsusf_mag_17Rnd_9x19_JHP",2,17],["SmokeShellYellow",2,1]]],["UK3CB_BAF_B_Bergen_MTP_JTAC_L_A",[["ACE_bloodIV",1],["ACE_bloodIV_250",1],["ACE_bloodIV_500",1],["ACE_CableTie",1],["ACE_EntrenchingTool",1],["ACE_Kestrel4500",1],["ACE_MapTools",1],["ACE_SpraypaintRed",1],["ACE_RangeCard",1],["SmokeShellYellow",4,1],["HandGrenade",3,1]]],"UK3CB_BAF_H_Beret_SAS_PRR","VSM_Shemagh_glasses_tan",["Laserdesignator_01_khk_F","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch",""]]};
	case "helicopterPilot": {_loadOut = [["SMA_M4afg_SM","","SMA_SFPEQ_M4TOP_BLK","SMA_ELCAN_SPECTER_ARDRDS_4z",["SMA_30Rnd_556x45_M855A1",30],[],""],[],["rhsusf_weap_glock17g4","rhsusf_acc_omega9k","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve",[["ACE_fieldDressing",16],["ACE_CableTie",1],["ACE_EarPlugs",1],["ACE_epinephrine",5],["ACE_Flashlight_XL50",1],["ACE_morphine",16]]],["UK3CB_BAF_V_Osprey_Rifleman_B",[["ACE_bloodIV_250",1],["ACE_bloodIV_500",1],["ACE_bloodIV",1],["ACE_EntrenchingTool",1],["ACE_MapTools",1],["SMA_30Rnd_556x45_M855A1",6,30],["SMA_30Rnd_556x45_M855A1_Tracer",2,30],["SmokeShellYellow",2,1],["SmokeShellGreen",2,1],["SmokeShellBlue",2,1],["HandGrenade",1,1],["Chemlight_green",2,1],["B_IR_Grenade",1,1]]],["tf_rt1523g",[]],"rhsusf_hgu56p_visor_black","VSM_Shemagh_Glasses_OD",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch",""]]};
	case "atSpecialist": {_loadOut = [["SMA_M4MOE_SM","SMA_supp2smaB_556","SMA_SFPEQ_M4TOP_BLK","SMA_ELCAN_SPECTER_RDS_4z",["SMA_30Rnd_556x45_M855A1",30],[],"SMA_Gripod_01"],["rhs_weap_maaws_optic","","","rhs_optic_maaws",["rhs_mag_maaws_HEAT",1],[],""],["rhsusf_weap_glock17g4","rhsusf_acc_omega9k","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve",[["ACE_fieldDressing",16],["ACE_CableTie",1],["ACE_EarPlugs",1],["ACE_epinephrine",5],["ACE_Flashlight_XL50",1],["ACE_morphine",16]]],["UK3CB_BAF_V_Osprey_Rifleman_D",[["SMA_30Rnd_556x45_M855A1",10,30],["SMA_30Rnd_556x45_M855A1_Tracer",4,30],["SmokeShellYellow",4,1],["HandGrenade",1,1]]],["UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D",[["ACE_bloodIV",1],["ACE_bloodIV_250",1],["ACE_bloodIV_500",1],["ACE_EntrenchingTool",1],["SmokeShellYellow",2,1],["HandGrenade",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",1,1],["rhs_mag_maaws_HE",1,1],["rhs_mag_maaws_HEAT",2,1]]],"UK3CB_BAF_H_Mk7_Scrim_F","VSM_Shemagh_glasses_tan",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch","ACE_NVG_Wide"]]};
	case "operator": {_loadOut = [["SMA_M4MOE_SM","SMA_supp2smaB_556","SMA_SFPEQ_M4TOP_BLK","SMA_ELCAN_SPECTER_RDS_4z",["SMA_30Rnd_556x45_M855A1",30],[],"SMA_Gripod_01"],["rhs_weap_M136","","","",["rhs_m136_mag",1],[],""],["rhsusf_weap_glock17g4","rhsusf_acc_omega9k","","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],["UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve",[["ACE_fieldDressing",16],["ACE_CableTie",1],["ACE_EarPlugs",1],["ACE_epinephrine",5],["ACE_Flashlight_XL50",1],["ACE_morphine",16]]],["UK3CB_BAF_V_Osprey_Rifleman_E",[["SMA_30Rnd_556x45_M855A1",10,30],["SMA_30Rnd_556x45_M855A1_Tracer",4,30],["SmokeShellYellow",4,1],["HandGrenade",1,1]]],["UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D",[["ACE_bloodIV",1],["ACE_bloodIV_250",1],["ACE_bloodIV_500",1],["ACE_CableTie",1],["ACE_EntrenchingTool",1],["Chemlight_blue",2,1],["B_IR_Grenade",2,1],["SmokeShellYellow",2,1],["HandGrenade",4,1]]],"UK3CB_BAF_H_Mk7_Scrim_F","VSM_Shemagh_Glasses_OD",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch","ACE_NVG_Wide"]]};
	case "eodTech": {_loadOut = [["SMA_M4afg_SM","SMA_supp2smaB_556","SMA_SFPEQ_M4TOP_BLK","SMA_ELCAN_SPECTER_RDS_4z",["SMA_30Rnd_556x45_M855A1",30],[],""],[],["ACE_VMH3","","","",[],[],""],["UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve",[["ACE_fieldDressing",16],["ACE_CableTie",1],["ACE_EarPlugs",1],["ACE_epinephrine",5],["ACE_Flashlight_XL50",1],["ACE_morphine",16]]],["UK3CB_BAF_V_Osprey_Rifleman_D",[["SMA_30Rnd_556x45_M855A1",10,30],["SMA_30Rnd_556x45_M855A1_Tracer",4,30],["SmokeShellYellow",2,1],["HandGrenade",2,1]]],["UK3CB_BAF_B_Bergen_MTP_Engineer_L_A",[["ACE_bloodIV",1],["ACE_bloodIV_250",1],["ACE_bloodIV_500",1],["ACE_DefusalKit",1],["ACE_EntrenchingTool",1],["ACE_M26_Clacker",1],["ACE_wirecutter",1],["SmokeShellYellow",2,1],["HandGrenade",3,1],["DemoCharge_Remote_Mag",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",1,1],["rhs_mag_mk84",2,1]]],"UK3CB_BAF_H_Mk7_Scrim_F","VSM_Shemagh_Glasses_OD",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch","ACE_NVG_Wide"]]};
	case "sarcMedic": {_loadOut = [["SMA_M4MOE_SM","SMA_supp2smaB_556","SMA_SFPEQ_M4TOP_BLK","SMA_ELCAN_SPECTER_RDS_4z",["SMA_30Rnd_556x45_M855A1",30],[],"SMA_Gripod_01"],[],["rhsusf_weap_glock17g4","rhsusf_acc_omega9k","","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],["UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve",[["ACE_fieldDressing",16],["ACE_CableTie",1],["ACE_EarPlugs",1],["ACE_epinephrine",5],["ACE_Flashlight_XL50",1],["ACE_morphine",16]]],["UK3CB_BAF_V_Osprey_Medic_D",[["ACE_EntrenchingTool",1],["SMA_30Rnd_556x45_M855A1",10,30],["SMA_30Rnd_556x45_M855A1_Tracer",4,30],["SmokeShellYellow",6,1],["HandGrenade",3,1]]],["UK3CB_BAF_B_Bergen_MTP_Medic_L_B",[["ACE_bloodIV",10],["ACE_bloodIV_250",10],["ACE_bloodIV_500",10],["ACE_fieldDressing",25],["ACE_epinephrine",5],["ACE_morphine",25],["ACE_EntrenchingTool",1],["Chemlight_blue",2,1],["B_IR_Grenade",1,1]]],"UK3CB_BAF_H_Mk7_Scrim_F","VSM_Shemagh_Glasses_OD",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch","ACE_NVG_Wide"]]};
	case "autoRiflemanM240B": {_loadOut = [["rhs_weap_m240B","ACE_muzzle_mzls_B","ACE_acc_pointer_green","rhsusf_acc_ACOG3",["rhsusf_100Rnd_762x51",100],[],""],[],["rhsusf_weap_glock17g4","rhsusf_acc_omega9k","","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve",[["ACE_fieldDressing",16],["ACE_CableTie",1],["ACE_EarPlugs",1],["ACE_epinephrine",5],["ACE_Flashlight_XL50",1],["ACE_morphine",16]]],["UK3CB_BAF_V_Osprey_MG_B",[["rhsusf_100Rnd_762x51_m80a1epr",2,100],["rhsusf_100Rnd_762x51_m62_tracer",3,100],["SmokeShellYellow",2,1],["HandGrenade",1,1]]],["UK3CB_BAF_B_Bergen_MTP_Rifleman_L_D",[["ACE_bloodIV",1],["ACE_bloodIV_250",1],["ACE_bloodIV_500",1],["ACE_EntrenchingTool",1],["SmokeShellYellow",4,1],["HandGrenade",2,1],["Chemlight_blue",2,1],["B_IR_Grenade",1,1],["rhsusf_100Rnd_762x51_m80a1epr",1,100],["rhsusf_100Rnd_762x51_m62_tracer",1,100],["rhsusf_100Rnd_762x51",1,100]]],"UK3CB_BAF_H_Mk7_Scrim_F","VSM_Shemagh_Glasses_OD",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","tf_anprc152","ItemCompass","ItemWatch","ACE_NVG_Wide"]]};
};

player setUnitLoadout _loadOut;

// WEAPON "SMA_M4_GL"
// SUPPRESSOR "SMA_supp2smaB_556"
// LASER? "SMA_SFPEQ_M4TOP_BLK"
// AMMO "SMA_30Rnd_556x45_M855A1"
// AMMO "1Rnd_HE_Grenade_shell"
// SCOPE "SMA_ELCAN_SPECTER_ARDRDS_4z"

// UNIFORM "UK3CB_BAF_U_CombatUniform_MTP_ShortSleeve"

// [this] spawn { 
	// params [["_crate",objNull]]; 
	// waitUntil {!(isNull _crate)}; 
	// clearBackpackCargoGlobal _crate;  
	// clearMagazineCargoGlobal _crate;  
	// clearWeaponCargoGlobal _crate;  
	// clearItemCargoGlobal _crate; 
	// _crate addAction ["AT Specialist (MAAWS) Class",{ [player,"atSpecialist"] execVM "scripts\SOG3playerClasses.sqf"; },[],9,true,true,"","true",5,false,"",""]; 
	// _crate addAction ["Auto Rifleman (M240B) Class",{ [player,"autoRiflemanM240B"] execVM "scripts\SOG3playerClasses.sqf"; },[],9,true,true,"","true",5,false,"",""]; 
	// _crate addAction ["Auto Rifleman (M249) Class",{ [player,"autoRiflemanM249"] execVM "scripts\SOG3playerClasses.sqf"; },[],9,true,true,"","true",5,false,"",""]; 
	// _crate addAction ["Combat Medic Class",{ [player,"combatMedic"] execVM "scripts\SOG3playerClasses.sqf"; },[],9,true,true,"","true",5,false,"",""]; 
	// _crate addAction ["Engineer Class",{ [player,"engineer"] execVM "scripts\SOG3playerClasses.sqf"; },[],9,true,true,"","true",5,false,"",""]; 
	// _crate addAction ["EOD Tech Class",{ [player,"eodTech"] execVM "scripts\SOG3playerClasses.sqf"; },[],9,true,true,"","true",5,false,"",""]; 
	// _crate addAction ["Grenadier Class",{ [player,"grenadier"] execVM "scripts\SOG3playerClasses.sqf"; },[],9,true,true,"","true",5,false,"",""]; 
	// _crate addAction ["Helicopter Pilot Class",{ [player,"helicopterPilot"] execVM "scripts\SOG3playerClasses.sqf"; },[],9,true,true,"","true",5,false,"",""]; 
	// _crate addAction ["JTAC Class",{ [player,"jtac"] execVM "scripts\SOG3playerClasses.sqf"; },[],9,true,true,"","true",5,false,"",""]; 
	// _crate addAction ["Operator Class",{ [player,"operator"] execVM "scripts\SOG3playerClasses.sqf"; },[],9,true,true,"","true",5,false,"",""]; 
	// _crate addAction ["SARC Medic Class",{ [player,"sarcMedic"] execVM "scripts\SOG3playerClasses.sqf"; },[],9,true,true,"","true",5,false,"",""]; 
	// _crate addAction ["Squad Leader Class",{ [player,"squadLeader"] execVM "scripts\SOG3playerClasses.sqf"; },[],9,true,true,"","true",5,false,"",""]; 
	// _crate addAction ["Team Leader Class",{ [player,"teamLeader"] execVM "scripts\SOG3playerClasses.sqf"; },[],9,true,true,"","true",5,false,"",""]; 
// };
